language: php

php:
  - 7.1
  - 7.2

env:
  - APP_ENV=testing
  - DB_DATABASE=database/database.sqlite

cache:
  directories:
    - vendor

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-source --no-interaction --dev

script:
  - cp .env.example .env
  - touch database/database.sqlite
  - php artisan key:generate
  - vendor/bin/phpunit
