language: php

php:
  - 7.1
  - 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-source --no-interaction --dev

script:
  - cp .env.example .env
  - php artisan key:generate
  - vendor/bin/phpunit
