language: php

php:
  - 7.1
  - 7.2

env:
  - APP_ENV=testing DB_CONNECTION=sqlite DB_DATABASE="database/database.sqlite"

cache:
  directories:
    - vendor

before_script:
  - composer install
  - touch database/database.sqlite
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate
  - php artisan passport:install

script:
  - vendor/bin/phpunit
