language: php

php:
  - 7.2

env:
  - APP_ENV=testing DB_CONNECTION=sqlite DB_DATABASE="database/database.sqlite"

cache:
  directories:
    - vendor

before_script:
  - travis_retry composer install --prefer-dist --no-interaction
  - touch database/database.sqlite
  - bin/install.sh
  - bin/reload-db.sh

script:
  - vendor/bin/phpunit  --testdox --verbose
