# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.2.1-fpm

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update 
          - apt-get install zip -y
          - apt-get install unzip -y
          - apt-get install libzip-dev -y
          - apt-get install jpegoptim -y
          - apt-get install optipng -y
          - apt-get install pngquant -y
          - apt-get install gifsicle -y
          - apt-get install libgmp3-dev -y
          - docker-php-ext-install zip
          - docker-php-ext-install gmp
          - docker-php-ext-install bcmath
          - export APP_ENV=testing
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - cp .env.example .env
          - php artisan key:generate
          - vendor/bin/phpunit 